/*select count(*),avg(t1.duration),avg(t2.duration) from index002 t1,index002 t2 where t1.ftype_stored=t2.ftype_stored and t1.ftype_storeTermVectors=t2.ftype_storeTermVectors and t1.ftype_storeTermVectorOffsets=t2.ftype_storeTermVectorOffsets and t1.ftype_storeTermVectorPositions=t2.ftype_storeTermVectorPositions and t1.ftype_storeTermVectorPayloads= t2.ftype_storeTermVectorPayloads and t1.ftype_omitNorms=t2.ftype_omitNorms and  t1.ftype_IndexOptions=t2.ftype_IndexOptions  and t1.ftype_numericType=t2.ftype_numericType and t1.ftype_docValuesType=t2.ftype_docValuesType and t1.dirType=t2.dirType and t1.ftype_tokenized!=t2.ftype_tokenized;*/

/*select count(*),avg(t1.duration),avg(t2.duration) from index002 t1,index002 t2 where t1.ftype_stored=t2.ftype_stored and t1.ftype_storeTermVectors=t2.ftype_storeTermVectors and t1.ftype_storeTermVectorOffsets=t2.ftype_storeTermVectorOffsets and t1.ftype_storeTermVectorPositions=t2.ftype_storeTermVectorPositions and t1.ftype_storeTermVectorPayloads= t2.ftype_storeTermVectorPayloads and t1.ftype_omitNorms=t2.ftype_omitNorms and  t1.ftype_IndexOptions=t2.ftype_IndexOptions  and t1.ftype_numericType=t2.ftype_numericType and t1.ftype_docValuesType=t2.ftype_docValuesType  and t1.ftype_tokenized=t2.ftype_tokenized and t1.id!=t2.id and t1.dirType!=t2.dirType;*/

/*select  t1.id,t2.id,t1.duration,t2.duration,t1.dirType,t2.dirType,t1.ftype_stored,t2.ftype_stored from index002 t1,index002 t2 where t1.ftype_stored!=t2.ftype_stored and t1.ftype_storeTermVectors=t2.ftype_storeTermVectors and t1.ftype_storeTermVectorOffsets=t2.ftype_storeTermVectorOffsets and t1.ftype_storeTermVectorPositions=t2.ftype_storeTermVectorPositions and t1.ftype_storeTermVectorPayloads= t2.ftype_storeTermVectorPayloads and t1.ftype_omitNorms=t2.ftype_omitNorms and  t1.ftype_IndexOptions=t2.ftype_IndexOptions  and t1.ftype_numericType=t2.ftype_numericType and t1.ftype_docValuesType=t2.ftype_docValuesType  and t1.ftype_tokenized=t2.ftype_tokenized and t1.id!=t2.id and t1.dirType=t2.dirType LIMIT 5;

select  avg(t1.duration) from index002 t1,index002 t2 where t1.ftype_stored!=t2.ftype_stored and t1.ftype_storeTermVectors=t2.ftype_storeTermVectors and t1.ftype_storeTermVectorOffsets=t2.ftype_storeTermVectorOffsets and t1.ftype_storeTermVectorPositions=t2.ftype_storeTermVectorPositions and t1.ftype_storeTermVectorPayloads= t2.ftype_storeTermVectorPayloads and t1.ftype_omitNorms=t2.ftype_omitNorms and  t1.ftype_IndexOptions=t2.ftype_IndexOptions  and t1.ftype_numericType=t2.ftype_numericType and t1.ftype_docValuesType=t2.ftype_docValuesType  and t1.ftype_tokenized=t2.ftype_tokenized and t1.id!=t2.id and t1.dirType=t2.dirType LIMIT 5;

select  avg(t2.duration) from index002 t1,index002 t2 where t1.ftype_stored!=t2.ftype_stored and t1.ftype_storeTermVectors=t2.ftype_storeTermVectors and t1.ftype_storeTermVectorOffsets=t2.ftype_storeTermVectorOffsets and t1.ftype_storeTermVectorPositions=t2.ftype_storeTermVectorPositions and t1.ftype_storeTermVectorPayloads= t2.ftype_storeTermVectorPayloads and t1.ftype_omitNorms=t2.ftype_omitNorms and  t1.ftype_IndexOptions=t2.ftype_IndexOptions  and t1.ftype_numericType=t2.ftype_numericType and t1.ftype_docValuesType=t2.ftype_docValuesType  and t1.ftype_tokenized=t2.ftype_tokenized and t1.id!=t2.id and t1.dirType=t2.dirType LIMIT 5;*/

use benchmark002;
select ftype_stored,ftype_tokenized,ftype_storeTermVectors,ftype_storeTermVectorOffsets,ftype_storeTermVectorPositions,ftype_storeTermVectorPayloads,ftype_omitNorms,ftype_IndexOptions,ftype_numericType, ftype_docValuesType,dirType,avg(duration) from index002 group by ftype_stored,ftype_tokenized,ftype_storeTermVectors,ftype_storeTermVectorOffsets,ftype_storeTermVectorPositions,ftype_storeTermVectorPayloads,ftype_omitNorms,ftype_IndexOptions,ftype_numericType, ftype_docValuesType,dirType order by ftype_stored,ftype_tokenized,ftype_storeTermVectors,ftype_storeTermVectorOffsets,ftype_storeTermVectorPositions,ftype_storeTermVectorPayloads,ftype_omitNorms,ftype_IndexOptions,ftype_numericType, ftype_docValuesType,dirType DESC;
